In [1]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5, 6], [ 7, 8, 9, 10, 11, 12]])
reshaped_arr = arr.reshape((4, 3))
print(reshaped_arr)
arr1, arr2 = np.split(reshaped_arr, 2)
print(arr1)
# print(arr1.shape)
# print(arr1.ndim)
# print(arr1.size)
# print(arr1.dtype)
# print(arr1.itemsize)
# print(arr1.data)
# print(arr1 + 1)
# print(arr1 * 2)
# print(arr1 ** 2)
# print(arr1 / 2)
# print(arr1 % 2)
# print(arr1 // 2)
print(arr1[0])
print(arr1[0][0])
print(arr1[0, 0])
print(arr1[0, :])
print(arr1[:, 0])
print(arr1[:, 0:2])

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(np.concatenate([arr1, arr2], axis=0))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[1 2 3]
 [4 5 6]]
[1 2 3]
1
1
[1 2 3]
[1 4]
[[1 2]
 [4 5]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


: 